### ISSUE TITLE
Question - Annotation Aggregation.ApplySupported.Transformation

### ISSUE THREAD

**Issue by Sheriwell** [SAP-samples/cloud-cap-risk-management#30]
In risks-analysis-service-ui.cds, there is an annotation "Aggregation.ApplySupported.Transformation" - however there seems to be no difference in behavior when Transformations is empty when I actually run CAP Node.js for OData V4.
https://github.com/SAP-samples/cloud-cap-risk-management/blob/analytics/srv/risks-analysis-service-ui.cds#L48

Why is this annotation configured on this code? I thought that if it was unnecessary, it could be cut down.

**Comment by kpadmapriya** [comment]
The transfromation can be used as explained in the [documentation](https://cap.cloud.sap/docs/advanced/odata#transformations)

However the scope of this tutorial did not implement them, as you mentioned, it does not make any difference in the result so that It can be used optionally.

Above documentaion is useful in case if you want to try further.

**Comment by Sheriwell** [comment]
Thank you for your answer. Now it is clear.
